// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Blog struct {
	ID          int64
	Title       string
	Content     string
	Description sql.NullString
	Slug        string
	CreatedAt   sql.NullTime
}
