// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (
    title, 
    content, 
    slug,
    description
) 
VALUES (?, ?, ?, ?)
RETURNING id, title, content, description, slug, created_at
`

type CreateBlogParams struct {
	Title       string
	Content     string
	Slug        string
	Description sql.NullString
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.Description,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs WHERE id = ?
`

func (q *Queries) DeleteBlog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlog, id)
	return err
}

const getBlog = `-- name: GetBlog :one
SELECT id, title, content, description, slug, created_at FROM blogs WHERE id = ?
`

func (q *Queries) GetBlog(ctx context.Context, id int64) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT id, title, content, description, slug, created_at FROM blogs WHERE slug = ?
`

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlogBySlug, slug)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, content, description, slug, created_at FROM blogs ORDER BY created_at
`

func (q *Queries) ListBlogs(ctx context.Context) ([]Blog, error) {
	rows, err := q.db.QueryContext(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Description,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs SET
    title = ?,
    description = ?,
    content = ?,
    slug = ?
WHERE id = ?
RETURNING id, title, content, description, slug, created_at
`

type UpdateBlogParams struct {
	Title       string
	Description sql.NullString
	Content     string
	Slug        string
	ID          int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, updateBlog,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Slug,
		arg.ID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Description,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
